#! /bin/sh
~/.fehbg &
picom &
setxkbmap -option caps:swapescape &
nm-applet &
blueman-applet &
sxhkd &
polybar default &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a *:scratchpad sticky=on state=floating hidden=on
while :
do
alacritty -d 120 50 --class scratchpad -e ~/scripts/scratch
done
