#! /bin/bash

# NOTE: daemon processes managed as systemd user services
# see ~/.config/systemd/user

/home/alec/scripts/autorandr
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $my_laptop_external_monitor = *connected* && ! $my_laptop_external_monitor = *disconnected* ]]; then
	bspc monitor eDP-1 -d 1 2 3 4 5
	bspc monitor HDMI-1 -d 6 7 8 9 0
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr
if test -z "$(setxkbmap -query | grep options:)"
then
	setxkbmap -option caps:swapescape
fi

if test -z "$(xset q | grep 'auto repeat delay:  350')"
then
	xset r rate 350 50
fi

~/.fehbg
/home/alec/scripts/launch-polybar

bspc config normal_border_color '#222222'
bspc config active_border_color '#000000'
bspc config focused_border_color '#fe8019'
bspc config border_width         2
bspc config top_padding          2
bspc config right_padding        2
bspc config bottom_padding       2
bspc config left_padding         2
# bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a *:scratchpad sticky=on state=floating hidden=on
while :
do
	alacritty --class scratchpad -e ~/scripts/scratch
done
