# alias ls="lsd"
alias ls="ls --color"
alias l="ls -la"
alias sudo="sudo -E "
alias mt="neomutt"
alias rexsrc="cd /home/alec/go/src/github.com/root-of-a-tree/remote_exec_bot"
alias luasrc="cd /home/alec/.local/share/nvim/site/pack/alec/start"
alias info="pinfo"
